# Generated by Django 4.1 on 2022-08-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automation",
            name="triggers",
        ),
        migrations.AddField(
            model_name="automation",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("opt_in", "opt_in"),
                    ("time_trigger", "time_trigger"),
                    ("removed_from_list", "removed_from_list"),
                    ("purchase_activity", "purchase_activity"),
                    ("list_trigger", "list_trigger"),
                    ("page_visited_trigger", "page_visited_trigger"),
                    ("register_seminar_trigger", "register_seminar_trigger"),
                ],
                default="opt_in",
                max_length=200,
            ),
        ),
    ]
